name: travesia_app
description: 'A Flutter travel app'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  flutter_secure_storage: ^9.2.2
  http: ^1.2.1
  image_picker: ^1.0.7
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  lottie: ^3.1.0
  flutter_svg: ^2.0.10
  carousel_slider: ^4.2.1
  animations: ^2.0.11
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
